version: "3.8"

services:
  #Eureka is not currently properly setup with docker swarm.
  discovery-service-d:
    build: ./discovery.service
    networks:
      - app-network
    image: discovery-service
    environment:
      eureka.instance.hostname: discovery-service-d
      eureka.client.serviceUrl.defaultZone: http://discovery-service-d:8761/eureka/
    healthcheck:
      test: curl -f http://localhost:8761 || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s

  interface-service-d:
    build: ./interface.service
    networks:
      - app-network
    ports:
      - "8081:8081"
    image: interface-service
    secrets:
      - google_api_key
    restart: on-failure:1
    environment:
      google.api.key: /run/secrets/google_api_key
      eureka.client.serviceUrl.defaultZone: http://discovery-service-d:8761/eureka/
    healthcheck:
      test: curl http://localhost:8081 || exit 1
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s

  stock-service-d:
    build: ./stock.service
    networks:
      - stock-network
      - app-network
    image: stock-service
    secrets:
      - mysql_user
      - mysql_password
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service-d:8761/eureka/
      db.username: /run/secrets/mysql_user
      db.password: /run/secrets/mysql_password
      db.host: db-stock:3306
    healthcheck:
      test: curl http://localhost:8084/stock || exit 1
      interval: 30s
      retries: 3
      timeout: 15s
      start_period: 90s

  db-stock:
    image: mysql:8.0.26
    networks:
      - stock-network
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: stock
    secrets:
      - mysql_user
      - mysql_password
    volumes:
      - stock-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 30s
      retries: 3
      timeout: 10s

  product-service-d:
    build: ./product.service
    networks:
      - product-network
      - app-network
    image: product-service
    secrets:
      - mysql_user
      - mysql_password
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service-d:8761/eureka/
      db.username: /run/secrets/mysql_user
      db.password: /run/secrets/mysql_password
      db.host: db-products:3306
    healthcheck:
      test: curl http://localhost:8083/products || exit 1
      interval: 30s
      retries: 3
      timeout: 15s
      start_period: 90s

  db-products:
    image: mysql:8.0.26
    networks:
      - product-network
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: products
    secrets:
      - mysql_user
      - mysql_password
    volumes:
      - product-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 30s
      retries: 3
      timeout: 10s

  price-service-d:
    build: ./price.service
    networks:
      - price-network
      - app-network
    image: price-service
    secrets:
      - mysql_user
      - mysql_password
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service-d:8761/eureka/
      db.username: /run/secrets/mysql_user
      db.password: /run/secrets/mysql_password
      db.host: db-price:3306
    healthcheck:
      test: curl http://localhost:8082/product-prices || exit 1
      interval: 30s
      retries: 3
      timeout: 15s
      start_period: 90s

  db-price:
    image: mysql:8.0.26
    networks:
      - price-network
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: product_prices
    secrets:
      - mysql_user
      - mysql_password
    volumes:
      - price-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 30s
      retries: 3
      timeout: 10s

secrets:
  mysql_user:
    file: ./mysql_user.txt
  mysql_password:
    file: ./mysql_password.txt
  google_api_key:
    file: ./google_api_key.txt

networks:
  app-network:
    driver: overlay
    attachable: true
  stock-network:
    driver: overlay
    attachable: true
  product-network:
    driver: overlay
    attachable: true
  price-network:
    driver: overlay
    attachable: true

volumes:
  stock-volume:
  price-volume:
  product-volume:
